controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    dynamic_controller:
      type: dynamic_controller/DynamicController


dynamic_controller:
  ros__parameters:
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
      - joint_7
    command_interfaces:
      - position
      - velocity
      - effort
      - control_word
    state_interfaces:
      - position
      - velocity
      - effort
      - status
    target_joints:
      - joint_1
      - joint_2
      #- joint_3
      - joint_4
      - joint_5
      - joint_6
      - joint_7
    module_ids:
      - 1
      - 2
      #- 3
      - 4
      - 5
      - 6
      - 7
    position_control_amplitudes:
      - 450000.0
      - 450000.0
      #- 450000.0
      - 450000.0
      - 450000.0
      - 450000.0
      - 450000.0
    position_control_frequencies:
      # 低速
      - 0.025
      - 0.025
      #- 0.025
      - 0.025
      - 0.025
      - 0.025
      - 0.025
    velocity_control_amplitudes:
      # 低速
      - 5000.0
      - 5000.0
      #- 5000.0
      - 5000.0
      - 5000.0
      - 5000.0
      - 5000.0
    velocity_control_frequencies:
      - 1.0
      - 1.0
      #- 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
    effort_control_amplitudes:
      # 低速
      - 1000.0
      - 1000.0
      #- 1000.0
      - 1000.0
      - 1000.0
      - 1000.0
      - 1000.0
    effort_control_frequencies:
      - 1.0
      - 1.0
      #- 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
    homing_velocity: 10000.0
    position_tolerance: 300.0
    