controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    position_controller:
      #type: position_controllers/JointGroupPositionController
      type: custom_position_controller/CustomPositionController

    velocity_controller:
      #type: velocity_controllers/JointGroupVelocityController
      type: custom_velocity_controller/CustomVelocityController

    effort_controller:
      #type: effort_controllers/JointGroupEffortController
      type: custom_effort_controller/CustomEffortController


position_controller:
  ros__parameters:
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
      - joint_7
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
      - effort
    target_joints:
      - joint_1
    amplitudes:
      - 300000.0
    frequencies:
      - 0.1
    homing_velocity: 10000.0
    position_tolerance: 300.0


trajectory_controller:
  ros__parameters:
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
      - joint_7
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
      - effort
    


velocity_controller:
  ros__parameters:
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
      - joint_7
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity
      - effort
    target_joints:
      - joint_1
    amplitudes:
      - 1000.0
    frequencies:
      - 0.1


effort_controller:
  ros__parameters:
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
      - joint_7
    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity
      - effort
    target_joints:
      - joint_1
    amplitudes:
      - 600.0
    frequencies:
      - 0.1