controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    position_controller:
      #type: position_controllers/JointGroupPositionController
      type: custom_position_controller/CustomPositionController

    velocity_controller:
      #type: velocity_controllers/JointGroupVelocityController
      type: custom_velocity_controller/CustomVelocityController

    effort_controller:
      #type: effort_controllers/JointGroupEffortController
      type: custom_effort_controller/CustomEffortController


position_controller:
  ros__parameters:
    joints:
      - left_joint_1
      - left_joint_2
      - left_joint_3
      - left_joint_4
      - left_joint_5
      - left_joint_6
      - left_joint_7
      - right_joint_1
      - right_joint_2
      - right_joint_3
      - right_joint_4
      - right_joint_5
      - right_joint_6
      - right_joint_7
    command_interfaces:
      - position
      - control_word
    state_interfaces:
      - position
      - velocity
      - effort
      - encoder_diff
    target_joints:
      - left_joint_1
      - left_joint_2
      - right_joint_4
      - right_joint_5
      #- left_joint_1
      #- left_joint_2
      #- left_joint_3
      #- left_joint_4
      #- left_joint_5
      #- left_joint_6
      #- left_joint_7
      #- right_joint_1
      #- right_joint_2
      #- right_joint_3
      #- right_joint_4
      #- right_joint_5
      #- right_joint_6
      #- right_joint_7
    amplitudes:
      - 100000.0
      - 100000.0
      - 100000.0
      - 100000.0
      #- 100000.0
      #- 100000.0
      #- 100000.0
      #- 100000.0
      #- 100000.0
      #- 100000.0
      #- 100000.0
      #- 100000.0
      #- 100000.0
      #- 100000.0
      #- 100000.0
      #- 100000.0
      #- 100000.0
      #- 100000.0
    frequencies:
      - 0.025
      - 0.025
      - 0.025
      - 0.025
      #- 0.025
      #- 0.025
      #- 0.025
      #- 0.025
      #- 0.025
      #- 0.025
      #- 0.025
      #- 0.025
      #- 0.025
      #- 0.025
      #- 0.025
      #- 0.025
      #- 0.025
      #- 0.025
    homing_velocity: 10000.0
    position_tolerance: 10000.0

trajectory_controller:
  ros__parameters:
    joints:
      - left_joint_1
      - left_joint_2
      - left_joint_3
      - left_joint_4
      - left_joint_5
      - left_joint_6
      - left_joint_7
      - right_joint_1
      - right_joint_2
      - right_joint_3
      - right_joint_4
      - right_joint_5
      - right_joint_6
      - right_joint_7
    command_interfaces:
      - position
    state_interfaces:
      - position


velocity_controller:
  ros__parameters:
    joints:
      - left_joint_1
      - left_joint_2
      - left_joint_3
      - left_joint_4
      - left_joint_5
      - left_joint_6
      - left_joint_7
      - right_joint_1
      - right_joint_2
      - right_joint_3
      - right_joint_4
      - right_joint_5
      - right_joint_6
      - right_joint_7
    command_interfaces:
      - velocity
      - control_word
    state_interfaces:
      - position
      - velocity
      - effort
      - encoder_diff
    target_joints:
      - left_joint_1
      - left_joint_2
      - right_joint_4
      - right_joint_5
      #- left_joint_1
      #- left_joint_2
      #- left_joint_3
      #- left_joint_4
      #- left_joint_5
      #- left_joint_6
      #- left_joint_7
      #- right_joint_1
      #- right_joint_2
      #- right_joint_3
      #- right_joint_4
      #- right_joint_5
      #- right_joint_6
      #- right_joint_7
    amplitudes:
      - 5000.0
      - 5000.0
      - 5000.0
      - 5000.0
      #- 5000.0
      #- 5000.0
      #- 5000.0
      #- 5000.0
      #- 5000.0
      #- 5000.0
      #- 5000.0
      #- 5000.0
      #- 5000.0
      #- 5000.0
      #- 5000.0
      #- 5000.0
      #- 5000.0
      #- 5000.0
    frequencies:
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      #- 1.0
      #- 1.0
      #- 1.0
      #- 1.0
      #- 1.0
      #- 1.0
      #- 1.0
      #- 1.0
      #- 1.0
      #- 1.0
      #- 1.0
      #- 1.0
      #- 1.0
      #- 1.0
    homing_velocity: 1000.0
    position_tolerance: 10000.0

effort_controller:
  ros__parameters:
    joints:
      - left_joint_1
      - left_joint_2
      - left_joint_3
      - left_joint_4
      - left_joint_5
      - left_joint_6
      - left_joint_7
      - right_joint_1
      - right_joint_2
      - right_joint_3
      - right_joint_4
      - right_joint_5
      - right_joint_6
      - right_joint_7
    command_interfaces:
      - effort
      - control_word
    state_interfaces:
      - position
      - velocity
      - effort
      - encoder_diff
    target_joints:
      - left_joint_1
      - left_joint_2
      - right_joint_4
      - right_joint_5
      #- left_joint_1
      #- left_joint_2
      #- left_joint_3
      #- left_joint_4
      #- left_joint_5
      #- left_joint_6
      #- left_joint_7
      #- right_joint_1
      #- right_joint_2
      #- right_joint_3
      #- right_joint_4
      #- right_joint_5
      #- right_joint_6
      #- right_joint_7
    amplitudes:
      - 1000.0
      - 1000.0
      - 1000.0
      - 1000.0
      #- 1000.0
      #- 1000.0
      #- 1000.0
      #- 1000.0
      #- 1000.0
      #- 1000.0
      #- 1000.0
      #- 1000.0
      #- 1000.0
      #- 1000.0
      #- 1000.0
      #- 1000.0
      #- 1000.0
      #- 1000.0
    frequencies:
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      #- 1.0
      #- 1.0
      #- 1.0
      #- 1.0
      #- 1.0
      #- 1.0
      #- 1.0
      #- 1.0
      #- 1.0
      #- 1.0
      #- 1.0
      #- 1.0
      #- 1.0
      #- 1.0
    homing_effort: 600.0
    position_tolerance: 10000.0