controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    position_controller:
      #type: position_controllers/JointGroupPositionController
      type: custom_position_controller/CustomPositionController

    velocity_controller:
      #type: velocity_controllers/JointGroupVelocityController
      type: custom_velocity_controller/CustomVelocityController

    effort_controller:
      #type: effort_controllers/JointGroupEffortController
      type: custom_effort_controller/CustomEffortController


position_controller:
  ros__parameters:
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
      - joint_7
    command_interfaces:
      - position
      - control_word
    state_interfaces:
      - position
      - velocity
      - effort
      - encoder_diff
    target_joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
      - joint_7
    amplitudes:
      - 450000.0
      - 450000.0
      - 450000.0
      - 450000.0
      - 450000.0
      - 450000.0
      - 450000.0
    frequencies:
      # 低速
      - 0.025
      - 0.025
      - 0.025
      - 0.025
      - 0.025
      - 0.025
      - 0.025
      # 中速
      #- 0.05
      #- 0.05
      #- 0.05
      #- 0.05
      #- 0.05
      #- 0.05
      #- 0.05
      # 高速
      #- 0.10
      #- 0.10
      #- 0.10
      #- 0.10
      #- 0.10
      #- 0.10
      #- 0.10
    homing_velocity: 10000.0
    position_tolerance: 300.0


trajectory_controller:
  ros__parameters:
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
      - joint_7
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
      - effort
    


velocity_controller:
  ros__parameters:
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
      - joint_7
    command_interfaces:
      - velocity
      - control_word
    state_interfaces:
      - position
      - velocity
      - effort
      - encoder_diff
    target_joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
      - joint_7
    amplitudes:
      # 低速
      - 5000.0
      - 5000.0
      - 5000.0
      - 5000.0
      - 5000.0
      - 5000.0
      - 5000.0
      # 中速
      #- 10000.0
      #- 10000.0
      #- 10000.0
      #- 10000.0
      #- 10000.0
      #- 10000.0
      #- 10000.0
      # 高速
      #- 30000.0
      #- 30000.0
      #- 30000.0
      #- 30000.0
      #- 30000.0
      #- 30000.0
      #- 30000.0
    frequencies:
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
    homing_velocity: 1000.0
    position_tolerance: 1000.0


effort_controller:
  ros__parameters:
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
      - joint_7
    command_interfaces:
      - effort
      - control_word
    state_interfaces:
      - position
      - velocity
      - effort
      - encoder_diff
    target_joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
      - joint_7
    amplitudes:
      # 低速
      - 1000.0
      - 1000.0
      - 1000.0
      - 1000.0
      - 1000.0
      - 1000.0
      - 1000.0
      # 中速
      #- 2000.0
      #- 2000.0
      #- 2000.0
      #- 2000.0
      #- 2000.0
      #- 2000.0
      #- 2000.0
      # 高速
      #- 3000.0
      #- 3000.0
      #- 3000.0
      #- 3000.0
      #- 3000.0
      #- 3000.0
      #- 3000.0
    frequencies:
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
    homing_effort: 600.0
    position_tolerance: 10000.0