# Configuration file for EasyCAT
vendor_id: 0x0000079A
product_id: 0xabe00001
assign_activate: 0x300 # DC Synch register
auto_fault_reset: true  # true = automatic fault reset, false = fault reset on rising edge command interface "reset_fault"

rpdo:  # RxPDO = receive PDO Mapping
  - index: 0x1600
    channels:
      - {index: 0x0005, sub_index: 1,  type: int32, default: .nan}
      - {index: 0x0005, sub_index: 2,  type: int32, default: .nan}
      - {index: 0x0005, sub_index: 3,  type: int32, default: .nan}
      - {index: 0x0005, sub_index: 4,  type: int32, default: .nan}
      - {index: 0x0005, sub_index: 5,  type: int32, default: .nan, command_interface: position} # Target position
      - {index: 0x0005, sub_index: 6,  type: int32, default: .nan}  
      - {index: 0x0005, sub_index: 7,  type: int32, default: .nan}  
      - {index: 0x0005, sub_index: 8,  type: int32, default: .nan}  
      - {index: 0x0005, sub_index: 9,  type: int32, default: .nan}  
      - {index: 0x0005, sub_index: 10, type: int32, default: .nan}  
      - {index: 0x0005, sub_index: 11, type: int32, default: .nan}  
      - {index: 0x0005, sub_index: 12, type: int32, default: .nan}  
      - {index: 0x0005, sub_index: 13, type: int32, default: .nan}  
      - {index: 0x0005, sub_index: 14, type: int32, default: .nan}  
      - {index: 0x0005, sub_index: 15, type: int32, default: .nan}  
      - {index: 0x0005, sub_index: 16, type: int32, default: .nan}  
      - {index: 0x0005, sub_index: 17, type: int32, default: .nan}  
      - {index: 0x0005, sub_index: 18, type: int32, default: .nan}  
      - {index: 0x0005, sub_index: 19, type: int32, default: .nan}  
      - {index: 0x0005, sub_index: 20, type: int32, default: .nan}  
      - {index: 0x0005, sub_index: 21, type: int32, default: .nan}  
      - {index: 0x0005, sub_index: 22, type: int32, default: .nan}  
      - {index: 0x0005, sub_index: 23, type: int32, default: .nan}  
      - {index: 0x0005, sub_index: 24, type: int32, default: .nan}  
      - {index: 0x0005, sub_index: 25, type: uint16, default: 0}
      - {index: 0x0005, sub_index: 26, type: uint16, default: 0}
      - {index: 0x0005, sub_index: 27, type: uint16, default: 0}
      - {index: 0x0005, sub_index: 28, type: uint16, default: 0}
      - {index: 0x0005, sub_index: 29, type: uint16, default: 0} # Control word
      - {index: 0x0005, sub_index: 30, type: uint16, default: 0}
      - {index: 0x0005, sub_index: 31, type: uint16, default: 0}
      - {index: 0x0005, sub_index: 32, type: uint16, default: 0}

tpdo:  # TxPDO = transmit PDO Mapping 
  - index: 0x1A00
    channels:
      - {index: 0x0006, sub_index: 1,  type: int32}
      - {index: 0x0006, sub_index: 2,  type: int32}
      - {index: 0x0006, sub_index: 3,  type: int32}
      - {index: 0x0006, sub_index: 4,  type: int32}
      - {index: 0x0006, sub_index: 5,  type: int32, state_interface: position}  # Position actual value
      - {index: 0x0006, sub_index: 6,  type: int32}
      - {index: 0x0006, sub_index: 7,  type: int32}
      - {index: 0x0006, sub_index: 8,  type: int32}  
      - {index: 0x0006, sub_index: 9,  type: int32}  
      - {index: 0x0006, sub_index: 10, type: int32}  
      - {index: 0x0006, sub_index: 11, type: int32}  
      - {index: 0x0006, sub_index: 12, type: int32}  
      - {index: 0x0006, sub_index: 13, type: int32, state_interface: velocity}  
      - {index: 0x0006, sub_index: 14, type: int32}  
      - {index: 0x0006, sub_index: 15, type: int32}  
      - {index: 0x0006, sub_index: 16, type: int32}  
      - {index: 0x0006, sub_index: 17, type: int32}  
      - {index: 0x0006, sub_index: 18, type: int32}  
      - {index: 0x0006, sub_index: 19, type: int32}  
      - {index: 0x0006, sub_index: 20, type: int32}  
      - {index: 0x0006, sub_index: 21, type: int32, state_interface: effort}  
      - {index: 0x0006, sub_index: 22, type: int32}  
      - {index: 0x0006, sub_index: 23, type: int32}  
      - {index: 0x0006, sub_index: 24, type: int32}  
      - {index: 0x0006, sub_index: 25, type: uint16}
      - {index: 0x0006, sub_index: 26, type: uint16}
      - {index: 0x0006, sub_index: 27, type: uint16}
      - {index: 0x0006, sub_index: 28, type: uint16}
      - {index: 0x0006, sub_index: 29, type: uint16} # Status word
      - {index: 0x0006, sub_index: 30, type: uint16}
      - {index: 0x0006, sub_index: 31, type: uint16}
      - {index: 0x0006, sub_index: 32, type: uint16}


      
sm:  # Sync Manager
  - {index: 2, type: output, pdo: rpdo, watchdog: enable}
  - {index: 3, type: input, pdo: tpdo, watchdog: disable}
