# Configuration file for EasyCAT
vendor_id: 0x0000079A
product_id: 0xabe00001
assign_activate: 0x300 # DC Synch register
auto_fault_reset: true  # true = automatic fault reset, false = fault reset on rising edge command interface "reset_fault"

rpdo:  # RxPDO = receive PDO Mapping
  - index: 0x1600
    channels:
      - {index: 0x0005, sub_index: 1,  type: int32, default: .nan} # Target position 1
      - {index: 0x0005, sub_index: 2,  type: int32, default: .nan} # Target position 2
      - {index: 0x0005, sub_index: 3,  type: int32, default: .nan} # Target position 3
      - {index: 0x0005, sub_index: 4,  type: int32, default: .nan} # Target position 4
      - {index: 0x0005, sub_index: 5,  type: int32, default: .nan} # Target position 5
      - {index: 0x0005, sub_index: 6,  type: int32, default: .nan} # Target position 6
      - {index: 0x0005, sub_index: 7,  type: int32, default: .nan} # Target position 7
      - {index: 0x0005, sub_index: 8,  type: int32, default: .nan} # Target position 8
      - {index: 0x0005, sub_index: 9,  type: int32, default: .nan} # Target velocity 1
      - {index: 0x0005, sub_index: 10, type: int32, default: .nan} # Target velocity 2
      - {index: 0x0005, sub_index: 11, type: int32, default: .nan} # Target velocity 3
      - {index: 0x0005, sub_index: 12, type: int32, default: .nan} # Target velocity 4
      - {index: 0x0005, sub_index: 13, type: int32, default: .nan} # Target velocity 5
      - {index: 0x0005, sub_index: 14, type: int32, default: .nan} # Target velocity 6
      - {index: 0x0005, sub_index: 15, type: int32, default: .nan} # Target velocity 7
      - {index: 0x0005, sub_index: 16, type: int32, default: .nan} # Target velocity 8
      - {index: 0x0005, sub_index: 17, type: int32, default: .nan} # Target torque 1
      - {index: 0x0005, sub_index: 18, type: int32, default: .nan} # Target torque 2
      - {index: 0x0005, sub_index: 19, type: int32, default: .nan, command_interface: effort} # Target torque 3
      - {index: 0x0005, sub_index: 20, type: int32, default: .nan} # Target torque 4
      - {index: 0x0005, sub_index: 21, type: int32, default: .nan} # Target torque 5
      - {index: 0x0005, sub_index: 22, type: int32, default: .nan} # Target torque 6
      - {index: 0x0005, sub_index: 23, type: int32, default: .nan} # Target torque 7
      - {index: 0x0005, sub_index: 24, type: int32, default: .nan} # Target torque 8
      - {index: 0x0005, sub_index: 25, type: uint16, default: 0} # Control word 1
      - {index: 0x0005, sub_index: 26, type: uint16, default: 0} # Control word 2
      - {index: 0x0005, sub_index: 27, type: uint16, default: 0} # Control word 3
      - {index: 0x0005, sub_index: 28, type: uint16, default: 0} # Control word 4
      - {index: 0x0005, sub_index: 29, type: uint16, default: 0} # Control word 5
      - {index: 0x0005, sub_index: 30, type: uint16, default: 0} # Control word 6
      - {index: 0x0005, sub_index: 31, type: uint16, default: 0} # Control word 7
      - {index: 0x0005, sub_index: 32, type: uint16, default: 0} # Control word 8

tpdo:  # TxPDO = transmit PDO Mapping 
  - index: 0x1A00
    channels:
      - {index: 0x0006, sub_index: 1,  type: int32} # Actual position 1
      - {index: 0x0006, sub_index: 2,  type: int32} # Actual position 2
      - {index: 0x0006, sub_index: 3,  type: int32, state_interface: position} # Actual position 3
      - {index: 0x0006, sub_index: 4,  type: int32} # Actual position 4
      - {index: 0x0006, sub_index: 5,  type: int32} # Actual position 5
      - {index: 0x0006, sub_index: 6,  type: int32} # Actual position 6
      - {index: 0x0006, sub_index: 7,  type: int32} # Actual position 7
      - {index: 0x0006, sub_index: 8,  type: int32} # Actual position 8
      - {index: 0x0006, sub_index: 9,  type: int32} # Actual velocity 1
      - {index: 0x0006, sub_index: 10, type: int32} # Actual velocity 2
      - {index: 0x0006, sub_index: 11, type: int32, state_interface: velocity} # Actual velocity 3
      - {index: 0x0006, sub_index: 12, type: int32} # Actual velocity 4
      - {index: 0x0006, sub_index: 13, type: int32} # Actual velocity 5
      - {index: 0x0006, sub_index: 14, type: int32} # Actual velocity 6
      - {index: 0x0006, sub_index: 15, type: int32} # Actual velocity 7
      - {index: 0x0006, sub_index: 16, type: int32} # Actual velocity 8
      - {index: 0x0006, sub_index: 17, type: int32} # Actual torque 1
      - {index: 0x0006, sub_index: 18, type: int32} # Actual torque 2
      - {index: 0x0006, sub_index: 19, type: int32, state_interface: effort} # Actual torque 3
      - {index: 0x0006, sub_index: 20, type: int32} # Actual torque 4
      - {index: 0x0006, sub_index: 21, type: int32} # Actual torque 5
      - {index: 0x0006, sub_index: 22, type: int32} # Actual torque 6
      - {index: 0x0006, sub_index: 23, type: int32} # Actual torque 7
      - {index: 0x0006, sub_index: 24, type: int32} # Actual torque 8
      - {index: 0x0006, sub_index: 25, type: uint16} # Status word 1
      - {index: 0x0006, sub_index: 26, type: uint16} # Status word 2
      - {index: 0x0006, sub_index: 27, type: uint16} # Status word 3
      - {index: 0x0006, sub_index: 28, type: uint16} # Status word 4
      - {index: 0x0006, sub_index: 29, type: uint16} # Status word 5
      - {index: 0x0006, sub_index: 30, type: uint16} # Status word 6
      - {index: 0x0006, sub_index: 31, type: uint16} # Status word 7
      - {index: 0x0006, sub_index: 32, type: uint16} # Status word 8
      
sm:  # Sync Manager
  - {index: 2, type: output, pdo: rpdo, watchdog: enable}
  - {index: 3, type: input, pdo: tpdo, watchdog: disable}
