# Configuration file for EasyCAT
vendor_id: 0x0000079A
product_id: 0xabe00001
assign_activate: 0x003c # DC Synch register
auto_fault_reset: true  # true = automatic fault reset, false = fault reset on rising edge command interface "reset_fault"

rpdo:  # RxPDO = receive PDO Mapping
  - index: 0x1600
    channels:
      - {index: 0x0005, sub_index: 1, type: int32, default: .nan} 
      - {index: 0x0005, sub_index: 2, type: int32, default: .nan}
      - {index: 0x0005, sub_index: 3, type: int32, default: .nan}
      - {index: 0x0005, sub_index: 4, type: int32, default: .nan}  
      - {index: 0x0005, sub_index: 5, type: int32, default: .nan, command_interface: position}  # Target position
      - {index: 0x0005, sub_index: 6, type: int32, default: .nan}  
      - {index: 0x0005, sub_index: 7, type: uint16, default: 0}  # Control word


tpdo:  # TxPDO = transmit PDO Mapping 
  - index: 0x1A00
    channels:
      - {index: 0x0006, sub_index: 1, type: int32}
      - {index: 0x0006, sub_index: 2, type: int32}
      - {index: 0x0006, sub_index: 3, type: int32}
      - {index: 0x0006, sub_index: 4, type: int32}
      - {index: 0x0006, sub_index: 5, type: int32, state_interface: position}  # Position actual value
      - {index: 0x0006, sub_index: 6, type: int32}
      - {index: 0x0006, sub_index: 7, type: uint16}  # Status word


      
sm:  # Sync Manager
  - {index: 2, type: output, pdo: rpdo, watchdog: enable}
  - {index: 3, type: input, pdo: tpdo, watchdog: disable}
